package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoGoods;
import org.myoranges.sotwo.db.domain.sotwoGoodsExample;

public interface SotwoGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoGoods> selectByExampleWithBLOBs(sotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoGoods> selectByExample(sotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoGoods> selectByExampleSelective(@Param("example") sotwoGoodsExample example, @Param("selective") sotwoGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoGoods record, @Param("example") sotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") sotwoGoods record, @Param("example") sotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoGoods record, @Param("example") sotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(sotwoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoGoods selectOneByExample(sotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoGoods selectOneByExampleSelective(@Param("example") sotwoGoodsExample example, @Param("selective") sotwoGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoGoods selectOneByExampleWithBLOBs(sotwoGoodsExample example);
}