package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoStorage;
import org.myoranges.sotwo.db.domain.SotwoStorageExample;

public interface SotwoStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    long countByExample(SotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int deleteByExample(SotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int insert(SotwoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int insertSelective(SotwoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    List<SotwoStorage> selectByExample(SotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoStorage> selectByExampleSelective(@Param("example") SotwoStorageExample example, @Param("selective") SotwoStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    SotwoStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoStorage record, @Param("example") SotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByExample(@Param("record") SotwoStorage record, @Param("example") SotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByPrimaryKey(SotwoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoStorage selectOneByExample(SotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoStorage selectOneByExampleSelective(@Param("example") SotwoStorageExample example, @Param("selective") SotwoStorage.Column ... selective);
}