package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoCoupon;
import org.myoranges.sotwo.db.domain.sotwoCouponExample;

public interface SotwoCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoCoupon> selectByExample(sotwoCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoCoupon> selectByExampleSelective(@Param("example") sotwoCouponExample example, @Param("selective") sotwoCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoCoupon record, @Param("example") sotwoCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoCoupon record, @Param("example") sotwoCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCoupon selectOneByExample(sotwoCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCoupon selectOneByExampleSelective(@Param("example") sotwoCouponExample example, @Param("selective") sotwoCoupon.Column ... selective);
}