package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoKeyword;
import org.myoranges.sotwo.db.domain.SotwoKeywordExample;

public interface SotwoKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    long countByExample(SotwoKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int deleteByExample(SotwoKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int insert(SotwoKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int insertSelective(SotwoKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    List<SotwoKeyword> selectByExample(SotwoKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoKeyword> selectByExampleSelective(@Param("example") SotwoKeywordExample example, @Param("selective") SotwoKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    SotwoKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoKeyword record, @Param("example") SotwoKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByExample(@Param("record") SotwoKeyword record, @Param("example") SotwoKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByPrimaryKey(SotwoKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoKeyword selectOneByExample(SotwoKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoKeyword selectOneByExampleSelective(@Param("example") SotwoKeywordExample example, @Param("selective") SotwoKeyword.Column ... selective);
}