package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoUser;
import org.myoranges.sotwo.db.domain.SotwoUserExample;

public interface SotwoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    long countByExample(SotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int deleteByExample(SotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int insert(SotwoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int insertSelective(SotwoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    List<SotwoUser> selectByExample(SotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoUser> selectByExampleSelective(@Param("example") SotwoUserExample example, @Param("selective") SotwoUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    SotwoUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoUser record, @Param("example") SotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExample(@Param("record") SotwoUser record, @Param("example") SotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKey(SotwoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoUser selectOneByExample(SotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoUser selectOneByExampleSelective(@Param("example") SotwoUserExample example, @Param("selective") SotwoUser.Column ... selective);
}