package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoUser;
import org.myoranges.sotwo.db.domain.sotwoUserExample;

public interface SotwoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoUser> selectByExample(sotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoUser> selectByExampleSelective(@Param("example") sotwoUserExample example, @Param("selective") sotwoUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoUser record, @Param("example") sotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoUser record, @Param("example") sotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoUser selectOneByExample(sotwoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoUser selectOneByExampleSelective(@Param("example") sotwoUserExample example, @Param("selective") sotwoUser.Column ... selective);
}