package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoCollect;
import org.myoranges.sotwo.db.domain.sotwoCollectExample;

public interface SotwoCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoCollect> selectByExample(sotwoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoCollect> selectByExampleSelective(@Param("example") sotwoCollectExample example, @Param("selective") sotwoCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoCollect record, @Param("example") sotwoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoCollect record, @Param("example") sotwoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCollect selectOneByExample(sotwoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCollect selectOneByExampleSelective(@Param("example") sotwoCollectExample example, @Param("selective") sotwoCollect.Column ... selective);
}