package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoCategory;
import org.myoranges.sotwo.db.domain.SotwoCategoryExample;


public interface SotwoCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(SotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(SotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(SotwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(SotwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<SotwoCategory> selectByExample(SotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoCategory> selectByExampleSelective(@Param("example") SotwoCategoryExample example, @Param("selective") SotwoCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    SotwoCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoCategory record, @Param("example") SotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") SotwoCategory record, @Param("example") SotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(SotwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoCategory selectOneByExample(SotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoCategory selectOneByExampleSelective(@Param("example") SotwoCategoryExample example, @Param("selective") SotwoCategory.Column ... selective);
}