package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoUserCoupon;
import org.myoranges.sotwo.db.domain.sotwoUserCouponExample;

public interface SotwoUserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoUserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoUserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoUserCoupon> selectByExample(sotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoUserCoupon> selectByExampleSelective(@Param("example") sotwoUserCouponExample example, @Param("selective") sotwoUserCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoUserCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoUserCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoUserCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoUserCoupon record, @Param("example") sotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoUserCoupon record, @Param("example") sotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoUserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoUserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoUserCoupon selectOneByExample(sotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoUserCoupon selectOneByExampleSelective(@Param("example") sotwoUserCouponExample example, @Param("selective") sotwoUserCoupon.Column ... selective);
}