package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoGoods;
import org.myoranges.sotwo.db.domain.SotwoGoodsExample;

public interface SotwoGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    long countByExample(SotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int deleteByExample(SotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int insert(SotwoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int insertSelective(SotwoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    List<SotwoGoods> selectByExampleWithBLOBs(SotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    List<SotwoGoods> selectByExample(SotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoGoods> selectByExampleSelective(@Param("example") SotwoGoodsExample example, @Param("selective") SotwoGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    SotwoGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoGoods record, @Param("example") SotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SotwoGoods record, @Param("example") SotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExample(@Param("record") SotwoGoods record, @Param("example") SotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SotwoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKey(SotwoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoGoods selectOneByExample(SotwoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoGoods selectOneByExampleSelective(@Param("example") SotwoGoodsExample example, @Param("selective") SotwoGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoGoods selectOneByExampleWithBLOBs(SotwoGoodsExample example);
}