package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoIssue;
import org.myoranges.sotwo.db.domain.sotwoIssueExample;

public interface SotwoIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoIssue> selectByExample(sotwoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoIssue> selectByExampleSelective(@Param("example") sotwoIssueExample example, @Param("selective") sotwoIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoIssue record, @Param("example") sotwoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoIssue record, @Param("example") sotwoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoIssue selectOneByExample(sotwoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoIssue selectOneByExampleSelective(@Param("example") sotwoIssueExample example, @Param("selective") sotwoIssue.Column ... selective);
}