package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoStorage;
import org.myoranges.sotwo.db.domain.sotwoStorageExample;

public interface SotwoStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoStorage> selectByExample(sotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoStorage> selectByExampleSelective(@Param("example") sotwoStorageExample example, @Param("selective") sotwoStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoStorage record, @Param("example") sotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoStorage record, @Param("example") sotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoStorage selectOneByExample(sotwoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoStorage selectOneByExampleSelective(@Param("example") sotwoStorageExample example, @Param("selective") sotwoStorage.Column ... selective);
}