package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoFootprint;
import org.myoranges.sotwo.db.domain.sotwoFootprintExample;

public interface SotwoFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoFootprint> selectByExample(sotwoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoFootprint> selectByExampleSelective(@Param("example") sotwoFootprintExample example, @Param("selective") sotwoFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoFootprint record, @Param("example") sotwoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoFootprint record, @Param("example") sotwoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoFootprint selectOneByExample(sotwoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoFootprint selectOneByExampleSelective(@Param("example") sotwoFootprintExample example, @Param("selective") sotwoFootprint.Column ... selective);
}