package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoOrder;
import org.myoranges.sotwo.db.domain.sotwoOrderExample;

public interface SotwoOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoOrder> selectByExample(sotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoOrder> selectByExampleSelective(@Param("example") sotwoOrderExample example, @Param("selective") sotwoOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoOrder record, @Param("example") sotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoOrder record, @Param("example") sotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoOrder selectOneByExample(sotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoOrder selectOneByExampleSelective(@Param("example") sotwoOrderExample example, @Param("selective") sotwoOrder.Column ... selective);
}