package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoRegionStreet;
import org.myoranges.sotwo.db.domain.sotwoRegionStreetExample;

public interface SotwoRegionStreetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoRegionStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoRegionStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoRegionStreet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoRegionStreet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoRegionStreet> selectByExample(sotwoRegionStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoRegionStreet> selectByExampleSelective(@Param("example") sotwoRegionStreetExample example, @Param("selective") sotwoRegionStreet.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoRegionStreet record, @Param("example") sotwoRegionStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoRegionStreet record, @Param("example") sotwoRegionStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoRegionStreet selectOneByExample(sotwoRegionStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoRegionStreet selectOneByExampleSelective(@Param("example") sotwoRegionStreetExample example, @Param("selective") sotwoRegionStreet.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_street
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoRegionStreet selectByPrimaryKeySelective(@Param("selective") sotwoRegionStreet.Column ... selective);
}