package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoRegionCity;
import org.myoranges.sotwo.db.domain.SotwoRegionCityExample;

public interface SotwoRegionCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    long countByExample(SotwoRegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int deleteByExample(SotwoRegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int insert(SotwoRegionCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int insertSelective(SotwoRegionCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    List<SotwoRegionCity> selectByExample(SotwoRegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoRegionCity> selectByExampleSelective(@Param("example") SotwoRegionCityExample example, @Param("selective") SotwoRegionCity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    SotwoRegionCity selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoRegionCity selectByPrimaryKeySelective(@Param("code") Integer code, @Param("selective") SotwoRegionCity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoRegionCity record, @Param("example") SotwoRegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByExample(@Param("record") SotwoRegionCity record, @Param("example") SotwoRegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoRegionCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByPrimaryKey(SotwoRegionCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoRegionCity selectOneByExample(SotwoRegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_city
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoRegionCity selectOneByExampleSelective(@Param("example") SotwoRegionCityExample example, @Param("selective") SotwoRegionCity.Column ... selective);
}