package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoRegionArea;
import org.myoranges.sotwo.db.domain.sotwoRegionAreaExample;

public interface SotwoRegionAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoRegionAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoRegionAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoRegionArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoRegionArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoRegionArea> selectByExample(sotwoRegionAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoRegionArea> selectByExampleSelective(@Param("example") sotwoRegionAreaExample example, @Param("selective") sotwoRegionArea.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoRegionArea record, @Param("example") sotwoRegionAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoRegionArea record, @Param("example") sotwoRegionAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoRegionArea selectOneByExample(sotwoRegionAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoRegionArea selectOneByExampleSelective(@Param("example") sotwoRegionAreaExample example, @Param("selective") sotwoRegionArea.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoRegionArea selectByPrimaryKeySelective(@Param("selective") sotwoRegionArea.Column ... selective);
}