package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoUserCoupon;
import org.myoranges.sotwo.db.domain.SotwoUserCouponExample;

public interface SotwoUserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    long countByExample(SotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int deleteByExample(SotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int insert(SotwoUserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int insertSelective(SotwoUserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    List<SotwoUserCoupon> selectByExample(SotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoUserCoupon> selectByExampleSelective(@Param("example") SotwoUserCouponExample example, @Param("selective") SotwoUserCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    SotwoUserCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoUserCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoUserCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoUserCoupon record, @Param("example") SotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExample(@Param("record") SotwoUserCoupon record, @Param("example") SotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoUserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKey(SotwoUserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoUserCoupon selectOneByExample(SotwoUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_user_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoUserCoupon selectOneByExampleSelective(@Param("example") SotwoUserCouponExample example, @Param("selective") SotwoUserCoupon.Column ... selective);
}