package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoRegion;
import org.myoranges.sotwo.db.domain.SotwoRegionExample;

public interface SotwoRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    long countByExample(SotwoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int deleteByExample(SotwoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int insert(SotwoRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int insertSelective(SotwoRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    List<SotwoRegion> selectByExample(SotwoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoRegion> selectByExampleSelective(@Param("example") SotwoRegionExample example, @Param("selective") SotwoRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    SotwoRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoRegion record, @Param("example") SotwoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExample(@Param("record") SotwoRegion record, @Param("example") SotwoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKey(SotwoRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoRegion selectOneByExample(SotwoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoRegion selectOneByExampleSelective(@Param("example") SotwoRegionExample example, @Param("selective") SotwoRegion.Column ... selective);
}