package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoAdmin;
import org.myoranges.sotwo.db.domain.sotwoAdminExample;

public interface SotwoAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoAdmin> selectByExample(sotwoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoAdmin> selectByExampleSelective(@Param("example") sotwoAdminExample example, @Param("selective") sotwoAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoAdmin record, @Param("example") sotwoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoAdmin record, @Param("example") sotwoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoAdmin selectOneByExample(sotwoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoAdmin selectOneByExampleSelective(@Param("example") sotwoAdminExample example, @Param("selective") sotwoAdmin.Column ... selective);
}