package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoAd;
import org.myoranges.sotwo.db.domain.SotwoAdExample;

public interface SotwoAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    long countByExample(SotwoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int deleteByExample(SotwoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int insert(SotwoAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int insertSelective(SotwoAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    List<SotwoAd> selectByExample(SotwoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoAd> selectByExampleSelective(@Param("example") SotwoAdExample example, @Param("selective") SotwoAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    SotwoAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoAd record, @Param("example") SotwoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByExample(@Param("record") SotwoAd record, @Param("example") SotwoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByPrimaryKey(SotwoAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoAd selectOneByExample(SotwoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoAd selectOneByExampleSelective(@Param("example") SotwoAdExample example, @Param("selective") SotwoAd.Column ... selective);
}