package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoCart;
import org.myoranges.sotwo.db.domain.sotwoCartExample;

public interface SotwoCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoCart> selectByExample(sotwoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoCart> selectByExampleSelective(@Param("example") sotwoCartExample example, @Param("selective") sotwoCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoCart record, @Param("example") sotwoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoCart record, @Param("example") sotwoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCart selectOneByExample(sotwoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCart selectOneByExampleSelective(@Param("example") sotwoCartExample example, @Param("selective") sotwoCart.Column ... selective);
}