package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoSearchHistory;
import org.myoranges.sotwo.db.domain.sotwoSearchHistoryExample;

public interface SotwoSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoSearchHistory> selectByExample(sotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoSearchHistory> selectByExampleSelective(@Param("example") sotwoSearchHistoryExample example, @Param("selective") sotwoSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoSearchHistory record, @Param("example") sotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoSearchHistory record, @Param("example") sotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoSearchHistory selectOneByExample(sotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoSearchHistory selectOneByExampleSelective(@Param("example") sotwoSearchHistoryExample example, @Param("selective") sotwoSearchHistory.Column ... selective);
}