package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoRegionProvince;
import org.myoranges.sotwo.db.domain.sotwoRegionProvinceExample;

public interface SotwoRegionProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoRegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoRegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoRegionProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoRegionProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoRegionProvince> selectByExample(sotwoRegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoRegionProvince> selectByExampleSelective(@Param("example") sotwoRegionProvinceExample example, @Param("selective") sotwoRegionProvince.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoRegionProvince selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoRegionProvince selectByPrimaryKeySelective(@Param("code") Integer code, @Param("selective") sotwoRegionProvince.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoRegionProvince record, @Param("example") sotwoRegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoRegionProvince record, @Param("example") sotwoRegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoRegionProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoRegionProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoRegionProvince selectOneByExample(sotwoRegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_region_province
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoRegionProvince selectOneByExampleSelective(@Param("example") sotwoRegionProvinceExample example, @Param("selective") sotwoRegionProvince.Column ... selective);
}