package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoProduct;
import org.myoranges.sotwo.db.domain.SotwoProductExample;

public interface SotwoProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    long countByExample(SotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int deleteByExample(SotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int insert(SotwoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int insertSelective(SotwoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    List<SotwoProduct> selectByExample(SotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoProduct> selectByExampleSelective(@Param("example") SotwoProductExample example, @Param("selective") SotwoProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    SotwoProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoProduct record, @Param("example") SotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByExample(@Param("record") SotwoProduct record, @Param("example") SotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    int updateByPrimaryKey(SotwoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoProduct selectOneByExample(SotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoProduct selectOneByExampleSelective(@Param("example") SotwoProductExample example, @Param("selective") SotwoProduct.Column ... selective);
}