package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoSearchHistory;
import org.myoranges.sotwo.db.domain.SotwoSearchHistoryExample;

public interface SotwoSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    long countByExample(SotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int deleteByExample(SotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int insert(SotwoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int insertSelective(SotwoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    List<SotwoSearchHistory> selectByExample(SotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoSearchHistory> selectByExampleSelective(@Param("example") SotwoSearchHistoryExample example, @Param("selective") SotwoSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    SotwoSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoSearchHistory record, @Param("example") SotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByExample(@Param("record") SotwoSearchHistory record, @Param("example") SotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated Fri May 11 22:05:05 CST 2018
     */
    int updateByPrimaryKey(SotwoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoSearchHistory selectOneByExample(SotwoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoSearchHistory selectOneByExampleSelective(@Param("example") SotwoSearchHistoryExample example, @Param("selective") SotwoSearchHistory.Column ... selective);
}