package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoProduct;
import org.myoranges.sotwo.db.domain.sotwoProductExample;

public interface SotwoProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoProduct> selectByExample(sotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoProduct> selectByExampleSelective(@Param("example") sotwoProductExample example, @Param("selective") sotwoProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoProduct record, @Param("example") sotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoProduct record, @Param("example") sotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoProduct selectOneByExample(sotwoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoProduct selectOneByExampleSelective(@Param("example") sotwoProductExample example, @Param("selective") sotwoProduct.Column ... selective);
}