package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoTopic;
import org.myoranges.sotwo.db.domain.SotwoTopicExample;


public interface SotwoTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(SotwoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(SotwoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(SotwoTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(SotwoTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<SotwoTopic> selectByExampleWithBLOBs(SotwoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<SotwoTopic> selectByExample(SotwoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoTopic> selectByExampleSelective(@Param("example") SotwoTopicExample example, @Param("selective") SotwoTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    SotwoTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoTopic record, @Param("example") SotwoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SotwoTopic record, @Param("example") SotwoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") SotwoTopic record, @Param("example") SotwoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SotwoTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(SotwoTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoTopic selectOneByExample(SotwoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoTopic selectOneByExampleSelective(@Param("example") SotwoTopicExample example, @Param("selective") SotwoTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoTopic selectOneByExampleWithBLOBs(SotwoTopicExample example);
}