package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.SotwoOrder;
import org.myoranges.sotwo.db.domain.SotwoOrderExample;


public interface SotwoOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(SotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(SotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(SotwoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(SotwoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<SotwoOrder> selectByExample(SotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SotwoOrder> selectByExampleSelective(@Param("example") SotwoOrderExample example, @Param("selective") SotwoOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    SotwoOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SotwoOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") SotwoOrder record, @Param("example") SotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") SotwoOrder record, @Param("example") SotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(SotwoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(SotwoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoOrder selectOneByExample(SotwoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sotwo_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SotwoOrder selectOneByExampleSelective(@Param("example") SotwoOrderExample example, @Param("selective") SotwoOrder.Column ... selective);
}