package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoComment;
import org.myoranges.sotwo.db.domain.sotwoCommentExample;

public interface SotwoCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoComment> selectByExample(sotwoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoComment> selectByExampleSelective(@Param("example") sotwoCommentExample example, @Param("selective") sotwoComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoComment record, @Param("example") sotwoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoComment record, @Param("example") sotwoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoComment selectOneByExample(sotwoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoComment selectOneByExampleSelective(@Param("example") sotwoCommentExample example, @Param("selective") sotwoComment.Column ... selective);
}