package org.myoranges.sotwo.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.myoranges.sotwo.db.domain.sotwoCategory;
import org.myoranges.sotwo.db.domain.sotwoCategoryExample;

public interface SotwoCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(sotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(sotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(sotwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(sotwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<sotwoCategory> selectByExample(sotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<sotwoCategory> selectByExampleSelective(@Param("example") sotwoCategoryExample example, @Param("selective") sotwoCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    sotwoCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") sotwoCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") sotwoCategory record, @Param("example") sotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") sotwoCategory record, @Param("example") sotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(sotwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(sotwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCategory selectOneByExample(sotwoCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    sotwoCategory selectOneByExampleSelective(@Param("example") sotwoCategoryExample example, @Param("selective") sotwoCategory.Column ... selective);
}