package org.myoranges.sotwo.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;

public class SotwoConsumeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_info.id
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_info.consume_log_id
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    private Integer consumeLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_info.user_id
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    private LocalDateTime userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_info.pay_status
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    private Integer payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_info.price
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_info.status
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_info.handler_time
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    private LocalDateTime handlerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_info.add_time
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_info.id
     *
     * @return the value of sotwo_consume_info.id
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_info.id
     *
     * @param id the value for sotwo_consume_info.id
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_info.consume_log_id
     *
     * @return the value of sotwo_consume_info.consume_log_id
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public Integer getConsumeLogId() {
        return consumeLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_info.consume_log_id
     *
     * @param consumeLogId the value for sotwo_consume_info.consume_log_id
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public void setConsumeLogId(Integer consumeLogId) {
        this.consumeLogId = consumeLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_info.user_id
     *
     * @return the value of sotwo_consume_info.user_id
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public LocalDateTime getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_info.user_id
     *
     * @param userId the value for sotwo_consume_info.user_id
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public void setUserId(LocalDateTime userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_info.pay_status
     *
     * @return the value of sotwo_consume_info.pay_status
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_info.pay_status
     *
     * @param payStatus the value for sotwo_consume_info.pay_status
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_info.price
     *
     * @return the value of sotwo_consume_info.price
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_info.price
     *
     * @param price the value for sotwo_consume_info.price
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_info.status
     *
     * @return the value of sotwo_consume_info.status
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_info.status
     *
     * @param status the value for sotwo_consume_info.status
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_info.handler_time
     *
     * @return the value of sotwo_consume_info.handler_time
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public LocalDateTime getHandlerTime() {
        return handlerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_info.handler_time
     *
     * @param handlerTime the value for sotwo_consume_info.handler_time
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public void setHandlerTime(LocalDateTime handlerTime) {
        this.handlerTime = handlerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_info.add_time
     *
     * @return the value of sotwo_consume_info.add_time
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_info.add_time
     *
     * @param addTime the value for sotwo_consume_info.add_time
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_consume_info
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", consumeLogId=").append(consumeLogId);
        sb.append(", userId=").append(userId);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", price=").append(price);
        sb.append(", status=").append(status);
        sb.append(", handlerTime=").append(handlerTime);
        sb.append(", addTime=").append(addTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_consume_info
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SotwoConsumeInfo other = (SotwoConsumeInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getConsumeLogId() == null ? other.getConsumeLogId() == null : this.getConsumeLogId().equals(other.getConsumeLogId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getPayStatus() == null ? other.getPayStatus() == null : this.getPayStatus().equals(other.getPayStatus()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getHandlerTime() == null ? other.getHandlerTime() == null : this.getHandlerTime().equals(other.getHandlerTime()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_consume_info
     *
     * @mbg.generated Sat May 12 10:41:29 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getConsumeLogId() == null) ? 0 : getConsumeLogId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getPayStatus() == null) ? 0 : getPayStatus().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getHandlerTime() == null) ? 0 : getHandlerTime().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        return result;
    }


    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sotwo_consume_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        consumeLogId("consume_log_id"),
        userId("user_id"),
        payStatus("pay_status"),
        price("price"),
        status("status"),
        handlerTime("handler_time"),
        addTime("add_time");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sotwo_consume_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sotwo_consume_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sotwo_consume_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sotwo_consume_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sotwo_consume_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sotwo_consume_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}