package org.myoranges.sotwo.db.domain;

import java.time.LocalDateTime;

public class SotwoConsumeLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_log.id
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_log.consume_title
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    private String consumeTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_log.consume_address
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    private String consumeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_log.consume_category_id
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    private Integer consumeCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_log.pay_user_id
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    private Integer payUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_log.price
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_log.reg_time
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    private LocalDateTime regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_log.status
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_log.handler_time
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    private LocalDateTime handlerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sotwo_consume_log.add_time
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    private LocalDateTime addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_log.id
     *
     * @return the value of sotwo_consume_log.id
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_log.id
     *
     * @param id the value for sotwo_consume_log.id
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_log.consume_title
     *
     * @return the value of sotwo_consume_log.consume_title
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public String getConsumeTitle() {
        return consumeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_log.consume_title
     *
     * @param consumeTitle the value for sotwo_consume_log.consume_title
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public void setConsumeTitle(String consumeTitle) {
        this.consumeTitle = consumeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_log.consume_address
     *
     * @return the value of sotwo_consume_log.consume_address
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public String getConsumeAddress() {
        return consumeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_log.consume_address
     *
     * @param consumeAddress the value for sotwo_consume_log.consume_address
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public void setConsumeAddress(String consumeAddress) {
        this.consumeAddress = consumeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_log.consume_category_id
     *
     * @return the value of sotwo_consume_log.consume_category_id
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public Integer getConsumeCategoryId() {
        return consumeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_log.consume_category_id
     *
     * @param consumeCategoryId the value for sotwo_consume_log.consume_category_id
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public void setConsumeCategoryId(Integer consumeCategoryId) {
        this.consumeCategoryId = consumeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_log.pay_user_id
     *
     * @return the value of sotwo_consume_log.pay_user_id
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public Integer getPayUserId() {
        return payUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_log.pay_user_id
     *
     * @param payUserId the value for sotwo_consume_log.pay_user_id
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public void setPayUserId(Integer payUserId) {
        this.payUserId = payUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_log.price
     *
     * @return the value of sotwo_consume_log.price
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_log.price
     *
     * @param price the value for sotwo_consume_log.price
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_log.reg_time
     *
     * @return the value of sotwo_consume_log.reg_time
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public LocalDateTime getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_log.reg_time
     *
     * @param regTime the value for sotwo_consume_log.reg_time
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public void setRegTime(LocalDateTime regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_log.status
     *
     * @return the value of sotwo_consume_log.status
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_log.status
     *
     * @param status the value for sotwo_consume_log.status
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_log.handler_time
     *
     * @return the value of sotwo_consume_log.handler_time
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public LocalDateTime getHandlerTime() {
        return handlerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_log.handler_time
     *
     * @param handlerTime the value for sotwo_consume_log.handler_time
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public void setHandlerTime(LocalDateTime handlerTime) {
        this.handlerTime = handlerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sotwo_consume_log.add_time
     *
     * @return the value of sotwo_consume_log.add_time
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sotwo_consume_log.add_time
     *
     * @param addTime the value for sotwo_consume_log.add_time
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_consume_log
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", consumeTitle=").append(consumeTitle);
        sb.append(", consumeAddress=").append(consumeAddress);
        sb.append(", consumeCategoryId=").append(consumeCategoryId);
        sb.append(", payUserId=").append(payUserId);
        sb.append(", price=").append(price);
        sb.append(", regTime=").append(regTime);
        sb.append(", status=").append(status);
        sb.append(", handlerTime=").append(handlerTime);
        sb.append(", addTime=").append(addTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_consume_log
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SotwoConsumeLog other = (SotwoConsumeLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getConsumeTitle() == null ? other.getConsumeTitle() == null : this.getConsumeTitle().equals(other.getConsumeTitle()))
            && (this.getConsumeAddress() == null ? other.getConsumeAddress() == null : this.getConsumeAddress().equals(other.getConsumeAddress()))
            && (this.getConsumeCategoryId() == null ? other.getConsumeCategoryId() == null : this.getConsumeCategoryId().equals(other.getConsumeCategoryId()))
            && (this.getPayUserId() == null ? other.getPayUserId() == null : this.getPayUserId().equals(other.getPayUserId()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getRegTime() == null ? other.getRegTime() == null : this.getRegTime().equals(other.getRegTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getHandlerTime() == null ? other.getHandlerTime() == null : this.getHandlerTime().equals(other.getHandlerTime()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sotwo_consume_log
     *
     * @mbg.generated Sat Jun 02 12:39:34 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getConsumeTitle() == null) ? 0 : getConsumeTitle().hashCode());
        result = prime * result + ((getConsumeAddress() == null) ? 0 : getConsumeAddress().hashCode());
        result = prime * result + ((getConsumeCategoryId() == null) ? 0 : getConsumeCategoryId().hashCode());
        result = prime * result + ((getPayUserId() == null) ? 0 : getPayUserId().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getRegTime() == null) ? 0 : getRegTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getHandlerTime() == null) ? 0 : getHandlerTime().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sotwo_consume_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        consumeTitle("consume_title"),
        consumeAddress("consume_address"),
        consumeCategoryId("consume_category_id"),
        payUserId("pay_user_id"),
        price("price"),
        regTime("reg_time"),
        status("status"),
        handlerTime("handler_time"),
        addTime("add_time");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sotwo_consume_log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sotwo_consume_log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sotwo_consume_log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sotwo_consume_log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sotwo_consume_log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sotwo_consume_log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}